### ISSUE TITLE
Receiving Report many times a day

### ISSUE THREAD

**Issue by JPAfflick** [streaka/report-writer-issues#19]
Josh, issue below still happening today, please look at again.

Northern Rocks is having the issue as described below.
Please fix as soon possible.

Can you please have someone look at an issue.
 
A Treatment Proposal we completed/uploaded with report writer is being continually sent to my mail inbox (approx.. 12 times a day).
 
Below is the form which needs attention.
 
Subterranean Termite Treatment Proposal submitted for C/- Defence Housing Australia - Darwin at 631 Stuart Hwy, Berrimah, NT

**Comment by jpike88** [comment]
related to database clogging... adding database worked and all should be fine now
