### ISSUE TITLE
Output Issue - Comments not displaying

### ISSUE THREAD

**Issue by JPAfflick** [streaka/report-writer-issues#25]
Was on Samsung Tablet.

Timber pest Inspection Report.

Info put into comments b=not showing on output when previewed or printed. See image attached.

![rw_bug_output](https://user-images.githubusercontent.com/29240808/28757905-506fd748-75d0-11e7-8bdf-07ecf7c67890.png)

**Comment by jpike88** [comment]
Weird, unable to reproduce this problem:

![screen shot 2017-07-31 at 2 14 53 pm](https://user-images.githubusercontent.com/9585787/28766630-a99a57ba-75fa-11e7-8277-1135ad4748a6.png)
 
If you can reproduce it, can you save it and I'll login as you and try to preview it?
