### ISSUE TITLE
Email Forwarding 

### ISSUE THREAD

**Issue by JPAfflick** [streaka/report-writer-issues#29]
Email forwarding Rules not working.

When you add user who's email you wish forwarded they disappear and then rules vanishes completely. 

You will see under Territory Pest Control account 3 rules that have no information associated with them, they are all blank.

**Comment by markstreaka** [comment]
@jpike88 can we look at this one today?

**Comment by JPAfflick** [comment]
Josh, this is still not working, I just changed everyone's email address and then went to add rule. The rule after submitting dissapears and is empty when looking into "edit rule". This empty rule is still inplace in Territory Pest if you would like to look at.

Need this fixed ASAP - 

see image below....
@jpike88 & @markstreaka 


![rw_bug](https://user-images.githubusercontent.com/29240808/31516426-3e8575e4-afe4-11e7-94c5-49500b349e15.png)

**Comment by markstreaka** [comment]
@jpike88 This is still not working for me either. Rows get added to Email Forwarding Rules table in dashboard but the rows contain zero data.

**Comment by jpike88** [comment]
Fixed (you'll need to create the rule for Territory Pest again)
